### ISSUE TITLE
Check the cert-manager setup

### ISSUE THREAD

**Issue by bsctl** [clastix/rancher-extension-clastix#1]
Currently the check on the cert-manager is based on the label of the cert-manager service.
Depending on how cert-manager is installed, this service can not be in place. It would better to check on the existence of CRD as we do for Kamaji.

**Comment by ludusrusso** [comment]
I'm looking for this crd: `certificates.cert-manager.io`

**Comment by bsctl** [comment]
@ludusrusso the fix is not working as the CRD is there but it is not detected.
![image](https://github.com/clastix/rancher-extension-clastix/assets/2222461/b244ac21-029e-4b78-8e2c-1826bede8fef)
