### ISSUE TITLE
Improve the start window of Kamaji Console

### ISSUE THREAD

**Issue by bsctl** [clastix/rancher-extension-clastix#2]
Currently the start window of Kamaji Console looks like this:

![image](https://github.com/clastix/rancher-extension-clastix/assets/2222461/b33c3a72-a46f-40d6-bf3a-afb095730a10)

Improve the windows so that:

- the left menu is displayed
-  the name of the cluster is displayed
-  the link is into a box with the proper icon

It should have the same look & feel of other extensions, for example:

![image](https://github.com/clastix/rancher-extension-clastix/assets/2222461/c22f475f-69cb-4662-9ee8-5f5a067fa6d6)

**Comment by ludusrusso** [comment]
![Screenshot 2023-07-02 alle 11 19 52](https://github.com/clastix/rancher-extension-clastix/assets/8146506/fc955c96-3235-4d6f-8fe6-68d5b9a66d4d)
@bsctl what do you think?
